### ISSUE TITLE
Bad state: Reflectable has not been initialized with the 2.022 version

### ISSUE THREAD

**Issue by cybertriton** [MikeMitterer/dryice#1]
E/flutter (15489): [ERROR:flutter/shell/common/shell.cc(181)] Dart Error: Unhandled exception:
E/flutter (15489): Bad state: Reflectable has not been initialized.
E/flutter (15489): Please make sure that the first action taken by your program
E/flutter (15489): in `main` is to call `initializeReflectable()`.
E/flutter (15489): #0      data (package:reflectable/src/reflectable_builder_based.dart:176:5)
E/flutter (15489): #1      data (package:reflectable/src/reflectable_builder_based.dart:175:33)
E/flutter (15489): #2      ReflectableImpl.reflectType (package:reflectable/src/reflectable_builder_based.dart:2507:26)
E/flutter (15489): #3      isInjectable (file:///Users/matrix/flutter/.pub-cache/hosted/pub.dartlang.org/dryice-2.0.22/lib/src/mirror_util.dart:54:42)
E/flutter (15489): #4      InjectorImpl.register (file:///Users/matrix/flutter/.pub-cache/hosted/pub.dartlang.org/dryice-2.0.22/lib/src/injector.dart:123:60)
E/flutter (15489): #5      Injector.bind (file:///Users/matrix/flutter/.pub-cache/hosted/pub.dartlang.org/dryice-2.0.22/lib/src/injector.dart:86:12)
E/flutter (15489): #6      DiContainer.bind (package:flutter_app/di_container.dart:30:17)
E/flutter (15489): #7      HarvestApp._init (file:///Users/matrix/Documents/GitHub/flutter_app/lib/main.dart:35:15)
E/flutter (15489): #8      new HarvestApp (file:///Users/matrix/Documents/GitHub/flutter_app/lib/main.dart:27:5)
E/flutter (15489): #9      main (file:///Users/matrix/Documents/GitHub/flutter_app/lib/main.dart:22:23)
E/flutter (15489): #10     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
E/flutter (15489): #11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
Syncing files to device Android SDK built for x86...

**Comment by MikeMitterer** [comment]
Check out this example: https://github.com/MikeMitterer/dryice/tree/master/samples/cmdline
